# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RCRSLogProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RCRSProto_pb2 as RCRSProto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RCRSLogProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\035rescuecore2.messages.protobufB\014RCRSLogProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12RCRSLogProto.proto\x1a\x0fRCRSProto.proto\"\x9e\x02\n\x08LogProto\x12\x1f\n\x05start\x18\x01 \x01(\x0b\x32\x0e.StartLogProtoH\x00\x12\x36\n\x10initialCondition\x18\x02 \x01(\x0b\x32\x1a.InitialConditionsLogProtoH\x00\x12#\n\x07\x63ommand\x18\x03 \x01(\x0b\x32\x10.CommandLogProtoH\x00\x12)\n\nperception\x18\x04 \x01(\x0b\x32\x13.PerceptionLogProtoH\x00\x12!\n\x06\x63onfig\x18\x05 \x01(\x0b\x32\x0f.ConfigLogProtoH\x00\x12\"\n\x06update\x18\x06 \x01(\x0b\x32\x10.UpdatesLogProtoH\x00\x12\x1b\n\x03\x65nd\x18\x07 \x01(\x0b\x32\x0c.EndLogProtoH\x00\x42\x05\n\x03log\"\x0f\n\rStartLogProto\";\n\x19InitialConditionsLogProto\x12\x1e\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x0c.EntityProto\"@\n\x0f\x43ommandLogProto\x12\x0c\n\x04time\x18\x01 \x01(\x05\x12\x1f\n\x08\x63ommands\x18\x02 \x03(\x0b\x32\r.MessageProto\"}\n\x12PerceptionLogProto\x12\x0c\n\x04time\x18\x01 \x01(\x05\x12\x10\n\x08\x65ntityID\x18\x02 \x01(\x05\x12 \n\x07visible\x18\x03 \x01(\x0b\x32\x0f.ChangeSetProto\x12%\n\x0e\x63ommunications\x18\x04 \x03(\x0b\x32\r.MessageProto\".\n\x0e\x43onfigLogProto\x12\x1c\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x0c.ConfigProto\"A\n\x0fUpdatesLogProto\x12\x0c\n\x04time\x18\x01 \x01(\x05\x12 \n\x07\x63hanges\x18\x02 \x01(\x0b\x32\x0f.ChangeSetProto\"\r\n\x0b\x45ndLogProtoB-\n\x1drescuecore2.messages.protobufB\x0cRCRSLogProtob\x06proto3'
  ,
  dependencies=[RCRSProto__pb2.DESCRIPTOR,])




_LOGPROTO = _descriptor.Descriptor(
  name='LogProto',
  full_name='LogProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='LogProto.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initialCondition', full_name='LogProto.initialCondition', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='LogProto.command', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='perception', full_name='LogProto.perception', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='LogProto.config', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update', full_name='LogProto.update', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='LogProto.end', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='log', full_name='LogProto.log',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=40,
  serialized_end=326,
)


_STARTLOGPROTO = _descriptor.Descriptor(
  name='StartLogProto',
  full_name='StartLogProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=343,
)


_INITIALCONDITIONSLOGPROTO = _descriptor.Descriptor(
  name='InitialConditionsLogProto',
  full_name='InitialConditionsLogProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entities', full_name='InitialConditionsLogProto.entities', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=404,
)


_COMMANDLOGPROTO = _descriptor.Descriptor(
  name='CommandLogProto',
  full_name='CommandLogProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='CommandLogProto.time', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='commands', full_name='CommandLogProto.commands', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=470,
)


_PERCEPTIONLOGPROTO = _descriptor.Descriptor(
  name='PerceptionLogProto',
  full_name='PerceptionLogProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='PerceptionLogProto.time', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entityID', full_name='PerceptionLogProto.entityID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visible', full_name='PerceptionLogProto.visible', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='communications', full_name='PerceptionLogProto.communications', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=597,
)


_CONFIGLOGPROTO = _descriptor.Descriptor(
  name='ConfigLogProto',
  full_name='ConfigLogProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='ConfigLogProto.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=645,
)


_UPDATESLOGPROTO = _descriptor.Descriptor(
  name='UpdatesLogProto',
  full_name='UpdatesLogProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='UpdatesLogProto.time', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='changes', full_name='UpdatesLogProto.changes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=647,
  serialized_end=712,
)


_ENDLOGPROTO = _descriptor.Descriptor(
  name='EndLogProto',
  full_name='EndLogProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=714,
  serialized_end=727,
)

_LOGPROTO.fields_by_name['start'].message_type = _STARTLOGPROTO
_LOGPROTO.fields_by_name['initialCondition'].message_type = _INITIALCONDITIONSLOGPROTO
_LOGPROTO.fields_by_name['command'].message_type = _COMMANDLOGPROTO
_LOGPROTO.fields_by_name['perception'].message_type = _PERCEPTIONLOGPROTO
_LOGPROTO.fields_by_name['config'].message_type = _CONFIGLOGPROTO
_LOGPROTO.fields_by_name['update'].message_type = _UPDATESLOGPROTO
_LOGPROTO.fields_by_name['end'].message_type = _ENDLOGPROTO
_LOGPROTO.oneofs_by_name['log'].fields.append(
  _LOGPROTO.fields_by_name['start'])
_LOGPROTO.fields_by_name['start'].containing_oneof = _LOGPROTO.oneofs_by_name['log']
_LOGPROTO.oneofs_by_name['log'].fields.append(
  _LOGPROTO.fields_by_name['initialCondition'])
_LOGPROTO.fields_by_name['initialCondition'].containing_oneof = _LOGPROTO.oneofs_by_name['log']
_LOGPROTO.oneofs_by_name['log'].fields.append(
  _LOGPROTO.fields_by_name['command'])
_LOGPROTO.fields_by_name['command'].containing_oneof = _LOGPROTO.oneofs_by_name['log']
_LOGPROTO.oneofs_by_name['log'].fields.append(
  _LOGPROTO.fields_by_name['perception'])
_LOGPROTO.fields_by_name['perception'].containing_oneof = _LOGPROTO.oneofs_by_name['log']
_LOGPROTO.oneofs_by_name['log'].fields.append(
  _LOGPROTO.fields_by_name['config'])
_LOGPROTO.fields_by_name['config'].containing_oneof = _LOGPROTO.oneofs_by_name['log']
_LOGPROTO.oneofs_by_name['log'].fields.append(
  _LOGPROTO.fields_by_name['update'])
_LOGPROTO.fields_by_name['update'].containing_oneof = _LOGPROTO.oneofs_by_name['log']
_LOGPROTO.oneofs_by_name['log'].fields.append(
  _LOGPROTO.fields_by_name['end'])
_LOGPROTO.fields_by_name['end'].containing_oneof = _LOGPROTO.oneofs_by_name['log']
_INITIALCONDITIONSLOGPROTO.fields_by_name['entities'].message_type = RCRSProto__pb2._ENTITYPROTO
_COMMANDLOGPROTO.fields_by_name['commands'].message_type = RCRSProto__pb2._MESSAGEPROTO
_PERCEPTIONLOGPROTO.fields_by_name['visible'].message_type = RCRSProto__pb2._CHANGESETPROTO
_PERCEPTIONLOGPROTO.fields_by_name['communications'].message_type = RCRSProto__pb2._MESSAGEPROTO
_CONFIGLOGPROTO.fields_by_name['config'].message_type = RCRSProto__pb2._CONFIGPROTO
_UPDATESLOGPROTO.fields_by_name['changes'].message_type = RCRSProto__pb2._CHANGESETPROTO
DESCRIPTOR.message_types_by_name['LogProto'] = _LOGPROTO
DESCRIPTOR.message_types_by_name['StartLogProto'] = _STARTLOGPROTO
DESCRIPTOR.message_types_by_name['InitialConditionsLogProto'] = _INITIALCONDITIONSLOGPROTO
DESCRIPTOR.message_types_by_name['CommandLogProto'] = _COMMANDLOGPROTO
DESCRIPTOR.message_types_by_name['PerceptionLogProto'] = _PERCEPTIONLOGPROTO
DESCRIPTOR.message_types_by_name['ConfigLogProto'] = _CONFIGLOGPROTO
DESCRIPTOR.message_types_by_name['UpdatesLogProto'] = _UPDATESLOGPROTO
DESCRIPTOR.message_types_by_name['EndLogProto'] = _ENDLOGPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogProto = _reflection.GeneratedProtocolMessageType('LogProto', (_message.Message,), {
  'DESCRIPTOR' : _LOGPROTO,
  '__module__' : 'RCRSLogProto_pb2'
  # @@protoc_insertion_point(class_scope:LogProto)
  })
_sym_db.RegisterMessage(LogProto)

StartLogProto = _reflection.GeneratedProtocolMessageType('StartLogProto', (_message.Message,), {
  'DESCRIPTOR' : _STARTLOGPROTO,
  '__module__' : 'RCRSLogProto_pb2'
  # @@protoc_insertion_point(class_scope:StartLogProto)
  })
_sym_db.RegisterMessage(StartLogProto)

InitialConditionsLogProto = _reflection.GeneratedProtocolMessageType('InitialConditionsLogProto', (_message.Message,), {
  'DESCRIPTOR' : _INITIALCONDITIONSLOGPROTO,
  '__module__' : 'RCRSLogProto_pb2'
  # @@protoc_insertion_point(class_scope:InitialConditionsLogProto)
  })
_sym_db.RegisterMessage(InitialConditionsLogProto)

CommandLogProto = _reflection.GeneratedProtocolMessageType('CommandLogProto', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDLOGPROTO,
  '__module__' : 'RCRSLogProto_pb2'
  # @@protoc_insertion_point(class_scope:CommandLogProto)
  })
_sym_db.RegisterMessage(CommandLogProto)

PerceptionLogProto = _reflection.GeneratedProtocolMessageType('PerceptionLogProto', (_message.Message,), {
  'DESCRIPTOR' : _PERCEPTIONLOGPROTO,
  '__module__' : 'RCRSLogProto_pb2'
  # @@protoc_insertion_point(class_scope:PerceptionLogProto)
  })
_sym_db.RegisterMessage(PerceptionLogProto)

ConfigLogProto = _reflection.GeneratedProtocolMessageType('ConfigLogProto', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGLOGPROTO,
  '__module__' : 'RCRSLogProto_pb2'
  # @@protoc_insertion_point(class_scope:ConfigLogProto)
  })
_sym_db.RegisterMessage(ConfigLogProto)

UpdatesLogProto = _reflection.GeneratedProtocolMessageType('UpdatesLogProto', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESLOGPROTO,
  '__module__' : 'RCRSLogProto_pb2'
  # @@protoc_insertion_point(class_scope:UpdatesLogProto)
  })
_sym_db.RegisterMessage(UpdatesLogProto)

EndLogProto = _reflection.GeneratedProtocolMessageType('EndLogProto', (_message.Message,), {
  'DESCRIPTOR' : _ENDLOGPROTO,
  '__module__' : 'RCRSLogProto_pb2'
  # @@protoc_insertion_point(class_scope:EndLogProto)
  })
_sym_db.RegisterMessage(EndLogProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
