#!/bin/bash

CIV_MIN=80
CIV_MAX=90
FB_MIN=10
FB_MAX=10
FS_MIN=0
FS_MAX=0
PF_MIN=20
PF_MAX=20
PO_MIN=0
PO_MAX=0
AT_MIN=10
AT_MAX=10
AC_MIN=0
AC_MAX=0
REFUGE_MIN=2
REFUGE_MAX=2
FIRE_MIN=3
FIRE_MAX=3

CLASSPATH=../jars/*:../lib/* java gis2.RandomScenarioGenerator $1 -civ $CIV_MIN $CIV_MAX -fb $FB_MIN $FB_MAX -fs $FS_MIN $FS_MAX -pf $PF_MIN $PF_MAX -po $PO_MIN $PO_MAX -at $AT_MIN $AT_MAX -ac $AC_MIN $AC_MAX -refuge $REFUGE_MIN $REFUGE_MAX -fire $FIRE_MIN $FIRE_MAX